steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_API_URL=https://electiq-backend-441154146170.us-central1.run.app'
      - '-t'
      - 'gcr.io/$PROJECT_ID/electiq-frontend:latest'
      - '.'
images:
  - 'gcr.io/$PROJECT_ID/electiq-frontend:latest'